url_rewrites:
  - match: "^https?:\\/\\/.+\\.pangolin-sdk-toutiao\\.com\\/api\\/ad\\/union\\/sdk\\/(get_ads|stats|settings)\\/"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.pglstatp-toutiao\\.com\\/.+\\/toutiao\\.mp4"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.(pglstatp-toutiao|pstatp)\\.com\\/(obj|img)\\/(ad-app-package|ad)\\/.+"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.(pglstatp-toutiao|pstatp)\\.com\\/(obj|img)\\/web\\.business\\.image\\/.+"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.(pglstatp-toutiao|pstatp)\\.com\\/obj\\/ad-pattern\\/renderer"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/gurd\\.snssdk\\.com\\/src\\/server\\/v3\\/package"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.byteimg.com/tos-cn-i-1yzifmftcy\\/(.+)-jpeg\\.jpeg"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.pstatp\\.com\\/obj\\/mosaic-legacy\\/.+\\?from\\=ad"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.pstatp\\.com\\/bytecom\\/resource\\/track-log\\/src\\/.+"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.snssdk\\.com\\/video\\/play\\/1\\/toutiao\\/.+\\/mp4"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.snssdk.com\\/api\\/ad\\/.+"
    location: "http://reject/"
    status_code: 307
  - match: "^http:\\/\\/.+\\.byteimg\\.com\\/ad-app-package"
    location: "http://reject/"
    status_code: 307
  - match: "^http:\\/\\/.+\\.byteimg\\.com\\/web\\.business\\.image"
    location: "http://reject/"
    status_code: 307
  - match: "^https?:\\/\\/.+?\\.snssdk\\.com\\/motor\\/operation\\/activity\\/display\\/config\\/V2\\/"
    location: "http://reject/"
    status_code: 307
  - match: "(?i)\\btc\\.qq\\.com\\/[\\w\\/\\.-]+[a-z]\\d+\\.mp4\\?"
    location: 'http://reject/'
    status_code: 307
  - match: "^https:\\/\\/god\\.gameyw\\.netease\\.com\\/v1\\/ad\\/.*"
    location: 'http://reject/'
    status_code: 307
  - match: "^https?:\\/\\/ads-img-al\\.xhscdn\\.com\\/hera/"
    location: 'http://reject/'
    status_code: 307
  - match: "^https?:\\/\\/cdn\\.fivecdm\\.com\\/cr/"
    location: 'http://reject/'
    status_code: 307
  - match: "^https?:\\/\\/m\\d\\.amap\\.com\\/ws\\/message\\/notice\\/list?"
    location: 'http://reject/'
    status_code: 307
  - match: "^https?:\\/\\/sns\\.amap\\.com\\/ws\\/msgbox\\/pull?"
    location: 'http://reject/'
    status_code: 307
  - match: "^https?:\\/\\/ssp\\.dzh\\.com\\.cn\\/v2api\\/adgroupjson"
    location: 'http://reject/'
    status_code: 307
mitm:
  hostnames:
    - '*.pangolin-sdk-toutiao'
    - '*.pangolin-sdk-toutiao.*'
    - '*.pstatp.com'
    - '*.pstatp.com.*'
    - '*.pglstatp-toutiao.com.*'
    - '*.pglstatp-toutiao.com'
    - 'gurd.snssdk.com'
    - 'gurd.snssdk.com.*'
    - '*default.ixigua.com'
    - '*.tiktokv.com'
    - '*.byteoversea.com'
    - '*.tik-tokapi.com'
