url_rewrites:
  - match: "^https?:\\/\\/.+\\.pangolin-sdk-toutiao\\.com\\/api\\/ad\\/union\\/sdk\\/(get_ads|stats|settings)\\/"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.pglstatp-toutiao\\.com\\/.+\\/toutiao\\.mp4"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.(pglstatp-toutiao|pstatp)\\.com\\/(obj|img)\\/(ad-app-package|ad)\\/.+"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.(pglstatp-toutiao|pstatp)\\.com\\/(obj|img)\\/web\\.business\\.image\\/.+"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.(pglstatp-toutiao|pstatp)\\.com\\/obj\\/ad-pattern\\/renderer"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/gurd\\.snssdk\\.com\\/src\\/server\\/v3\\/package"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.byteimg.com/tos-cn-i-1yzifmftcy\\/(.+)-jpeg\\.jpeg"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.pstatp\\.com\\/obj\\/mosaic-legacy\\/.+\\?from\\=ad"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.pstatp\\.com\\/bytecom\\/resource\\/track-log\\/src\\/.+"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.snssdk\\.com\\/video\\/play\\/1\\/toutiao\\/.+\\/mp4"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+\\.snssdk.com\\/api\\/ad\\/.+"
    location: "reject"
    status_code: 307
  - match: "^http:\\/\\/.+\\.byteimg\\.com\\/ad-app-package"
    location: "reject"
    status_code: 307
  - match: "^http:\\/\\/.+\\.byteimg\\.com\\/web\\.business\\.image"
    location: "reject"
    status_code: 307
  - match: "^https?:\\/\\/.+?\\.snssdk\\.com\\/motor\\/operation\\/activity\\/display\\/config\\/V2\\/"
    location: "reject"
    status_code: 307
  - match: "(?<=_region=)CN(?=&)"
    location: 'JP'
    status_code: 307
  - match: "(?<=&mcc_mnc=)4"
    location: '2'
    status_code: 307
  - match: "^(https?:\\/\\/(tnc|dm)[\\w-]+\\.\\w+\\.com\\/.+)(\\?)(.+)"
    location: '$1$3'
    status_code: 302
  - match: "(^https?:\\/\\/*\\.\\w{4}okv.com\\/.+&.+)(\\d{2}\\.3\\.\\d)(.+)"
    location: '$118.0$3'
    status_code: 302

mitm:
  hostnames: 
    - '*.pangolin-sdk-toutiao'
    - '*.pangolin-sdk-toutiao.*'
    - '*.pstatp.com'
    - '*.pstatp.com.*'
    - '*.pglstatp-toutiao.com.*'
    - '*.pglstatp-toutiao.com'
    - 'gurd.snssdk.com'
    - 'gurd.snssdk.com.*'
    - '*default.ixigua.com'
    - '*.tiktokv.com'
    - '*.byteoversea.com'
    - '*.tik-tokapi.com'